config/urls.py
from django.contrib import admin
from django.urls import path, include

from hi import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('common/', include('common.urls')),
    path('crawling', include('crawling.urls')),
    path('', include('hi.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hi/urls.py
from django.urls import path

from . import views

app_name = 'hi'

urlpatterns = [

path('', views.index, name='index'),
path('loginsu/', views.loginsu, name='loginsu'),

]

main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [

    path('board/', views.iindex, name='iindex'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

]


main/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Photo(models.Model):

    post = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

class Answer(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    modify_date = models.DateTimeField(null=True, blank=True)

# Create your models here.

main/forms.py
from django import forms
from main.models import Question, Answer, Photo

class QuestionForm(forms.ModelForm):

    class Meta:

        model = Question
        fields = ['subject', 'content']

        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):

    class Meta:

        model = Answer
        fields = ['content']

        labels = {
            'content': '답변내용',
        }

main/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Question, Answer, Photo
from .forms import QuestionForm, AnswerForm
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from django.db.models import Q

def iindex(request):

    if request.user.is_authenticated:

        page = request.GET.get('page', '1')
        question_list = Question.objects.order_by('-create_date')

        kw = request.GET.get('kw', '')
        if kw:
            question_list = question_list.filter(
                Q(subject__icontains=kw) |  # 제목 검색
                Q(content__icontains=kw) |  # 내용 검색
                Q(answer__content__icontains=kw) |  # 답변 내용 검색
                Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
                Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            ).distinct()

        paginator = Paginator(question_list, 10)
        page_obj = paginator.get_page(page)

        context = {'question_list': page_obj}

        return render(request, 'main/question_list.html', context)

    else:

        return render(request, 'boarderr.html')

def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}

    return render(request, 'main/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":

        form = AnswerForm(request.POST)

        if form.is_valid():

            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()

            answer.question = question
            answer.save()

            return redirect('main:detail', question_id=question.id)

    else:

        return HttpResponseNotAllowed('Only POST is possible.')

    context = {'question': question, 'form': form}

    return render(request, 'main/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):

    if request.method == 'POST':

        form = QuestionForm(request.POST)

        if form.is_valid():

            question = form.save(commit=False)

            question.author = request.user

            question.create_date = timezone.now()

            question.save()

            for img in request.FILES.getlist('imgs'):

                photo = Photo()
                photo.post = question
                photo.image = img
                photo.save()

            return redirect('main:iindex')

    else:

        form = QuestionForm()

    context = {'form': form}

    return render(request, 'main/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    if request.user != question.author:

        messages.error(request, '수정권한이 없음')

        return redirect('main:detail', question_id=question.id)

    if request.method == "POST":

        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():

            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()

            return redirect('main:detail', question_id=question.id)

    else:

        form = QuestionForm(instance=question)

    context = {'form': form}

    return render(request, 'main/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    if request.user != question.author:

        messages.error(request, '삭제권한이 없음')

        return redirect('main:detail', question_id=question.id)

    question.delete()

    return redirect('main:iindex')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:

        messages.error(request, '수정권한이 없음')

        return redirect('main:detail', question_id=answer.question.id)

    if request.method == "POST":

        form = AnswerForm(request.POST, instance=answer)

        if form.is_valid():

            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()

            return redirect('main:detail', question_id=answer.question.id)

    else:

        form = AnswerForm(instance=answer)

    context = {'answer': answer, 'form': form}

    return render(request, 'main/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:

        messages.error(request, '삭제권한이 없음')

    else:

        answer.delete()

    return redirect('main:detail', question_id=answer.question.id)

# Create your views here.

templates/main/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">

    <form method="post">

        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>

    </form>

</div>
{% endblock %}

templates/main/question_detail.html
<style>

    #test {
    margin-top: 100px;
    margin-left: 100px;
    }

</style>

{% extends 'base.html' %}
{% block content %}

<div id="test">

<div class="container my-3">

    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">{% if request.user == question.author %}
                <a href="{% url 'main:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'main:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% for photo in question.photo_set.all %}
        <img src="{{photo.image.url}}" width="200" heigh=20"><br>
    {% endfor %}

    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                    <a href="{% url 'main:answer_modify' answer.id  %}"
                        class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                        data-uri="{% url 'main:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
        </div>
        </div>
    </div>
    {% endfor %}

    <form action="{% url 'main:answer_create' question.id %}" method="post" class="my-3">

        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">

            {% for field in form %}

            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}

            {% endfor %}

        </div>
        {% endif %}

        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>

        <button type="button" onClick="location.href='/main/board'" class="btn btn-primary">
            <div>목록보기</div>
        </button>

        <input type="submit" value="답변등록" class="btn btn-primary">

    </form>

</div>
{% endblock %}
    {% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/main/question_form.html
<style>

    #test {
    margin-top: 100px;
    margin-left: 100px;
    }

</style>

{% extends 'base.html' %}
{% block content %}

<div id="test">

<div class="container">

    <h5 class="my-3 border-bottom pb-2">질문등록</h5>

    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">

            {% for field in form %}

            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}

            {% endfor %}

        </div>
        {% endif %}

        <div class="mb-3">

            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">

        </div>

        <div class="mb-3">

            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>

        </div>

        <div class="mb-3">

            <label for="text" class="form-label">사진</label>
            <input type="file" name="imgs" multiple>

        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>

    </form>

</div>
{% endblock %}

templates/main/question_list.html
<style>

    #test {
    margin-top: 100px;
    margin-left: 100px;
    }

    .input-group {
    text-align: right;
    }

</style>

{% extends 'base.html' %}

{% load main_filter %}

{% block content %}
<div id="test">

    <div class="container my-3">

        <div class="row my-3">

            <div class="col-6">

                <div class="input-group" id="test2">

                    <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">

                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                    </div>

                </div>

            </div>

        </div>

        <table class="table">

            <thead>

            <tr class="text-center table-dark">

                <th>번호</th>

                <th style="width:50%">제목</th>

                <th>글쓴이</th>

                <th>작성일시</th>

            </tr>

            </thead>

            <tbody>

            {% if question_list %}
            {% for question in question_list %}
            <tr class="text-center">

                <td>

                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}

                </td>

                <td class="text-start">

                    <a href="{% url 'main:detail' question.id %}">{{ question.subject }}</a>

                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                    {% endif %}

                </td>

                <td>{{ question.author.username }}</td>

                <td>{{ question.create_date }}</td>

            </tr>
            {% endfor %}
            {% else %}
            <tr>

                <td colspan="4">질문이 없습니다.</td>

            </tr>
            {% endif %}

            </tbody>

        </table>



            <div class="col-6">
                <a href="{% url 'main:question_create' %}" class="btn btn-primary">질문 등록하기</a>
            </div>



        <ul class="pagination justify-content-center text-centen">

            <!-- 이전 -->
            {% if question_list.has_previous %}
            <li class="page-item">

                <a class="page-link" href="?page={{ question_list.previous_page_number }}"
                    href="javascript:void(0)">이전</a>

            </li>

            <!-- 이전 없음 -->
            {% else %}

            <li class="page-item disabled">

                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>

            </li>
            {% endif %}

            <!-- 페이지 리스트 -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">

                <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>

            </li>

            {% else %}
            <li class="page-item">

                <a class="page-link" data-page="{{ page_number }}"
                   href="javascript:void(0)">{{ page_number }}</a>

            </li>
            {% endif %}
            {% endif %}
            {% endfor %}

            <!-- 다음 -->
            {% if question_list.has_next %}
            <li class="page-item">

                <a class="page-link" data-page="{{ question_list.next_page_number }}"
                   href="javascript:void(0)">다음</a>

            </li>

            {% else %}
            <li class="page-item disabled">

                <a class="page-link" tabindex="-1" aria-disabled="true"
                   href="javascript:void(0)">다음</a>

            </li>
            {% endif %}

        </ul>

    </div>

    <form id="searchForm" method="get" action="{% url 'main:iindex' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>

</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>

const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});

const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});

</script>
{% endblock %}