common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from hi import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('common/', include('common.urls')),
    path('crawling', include('crawling.urls')),
    path('', include('hi.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawling/urls.py
from django.urls import path, include

from . import views

app_name = 'crawling'

urlpatterns = [

    path('crawling/', views.crawling, name='crawling'),
    path('crawlingsubject/', views.crawlingsubject, name='crawlingsubject'),

]

hi/urls.py
from django.urls import path

from . import views

app_name = 'hi'

urlpatterns = [

path('', views.index, name='index'),
path('loginsu/', views.loginsu, name='loginsu'),

]

main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [

    path('board/', views.iindex, name='iindex'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

]


hi/models.py
from django.db import models

# Create your models here.

hi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

def index(request):

    return render(request, 'hi.html')

def loginsu(request):

    return render(request, 'loginsu.html')

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- assign CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, Hightop!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</div>
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/boarderr.html
{% extends "base.html" %}
{% block content %}

{% if not user.is_authenticated %}

    <script>

        alert("먼저 로그인이나 회원 가입부터");

    </script>

{% endif %}

{% endblock %}

templates/form_errors.html
{% if form.errors %}

    {% if user.is_authenticated %}

    {% else %}

        <script type=""text/javascript">

            alert('로그인 실패')

        </script>

    {% endif %}

    <div class="alert alert-danger">

        {% for field in form %}
        {% if field.errors %}

            <div>

                <strong>{{ field.label }}</strong>

                {{ field.errors }}

            </div>

        {% endif %}
        {% endfor %}

        {% for error in form.non_field_errors %}
        <div>

            <strong>{{ error }}</strong>

        </div>
        {% endfor %}

    </div>

{% endif %}

templates/hi.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

templates/loginsu.html
{% extends "base.html" %}
{% block content %}

{% if user.is_authenticated %}

    <script>

        alert("로그인 성공");

    </script>

{% endif %}

{% endblock %}

templates/navbar.html
<html>
<head>
    <meta charset="utf-8">
    <title>Menubar</title>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:400,700,500);

        /* main Styles */

        html { box-sizing: border-box; }

        *, *:before, *:after { box-sizing: inherit; }

        body {
            background-image: url('https://cdn.pixabay.com/photo/2021/01/29/08/08/dog-5960092_960_720.jpg');
            background-repeat: no-repeat;
            background-size: cover;

            font-family: "Roboto", sans-serif;
            font-size: 14px;
            margin: 0;
        }

        a { text-decoration: none; }

        .container {
            width: 1000px;
            margin: 0px;
        }

        h1 { text-align:center; margin-top:0px;}

        /* Navigation Styles */

        nav { background: #2ba0db; }

        nav ul {
            font-size: 0;
            margin: 0;
            padding: 0;
        }

        nav ul li {
            display: inline-block;
            position: relative;
        }

        nav ul li a {
            color: #fff;
            display: block;
            font-size: 25px;
            padding: 15px 14px;
            transition: 0.3s linear;
        }

        nav ul li:hover { background: #126d9b; }

        nav ul li ul {
            border-bottom: 5px solid #2ba0db;
            display: none;
            position: absolute;
            width: 250px;
        }

        nav ul li ul li {
            border-top: 1px solid #444;
            display: block;
        }

        nav ul li ul li:first-child { border-top: none; }

        nav ul li ul li a {
            background: #373737;
            display: block;
            padding: 10px 14px;
        }

        nav ul li ul li a:hover { background: #126d9b; }

        nav .fa.fa-angle-down { margin-left: 6px; }

    </style>

</head>

<body>
<nav>

    <div class="container">

        <ul>

            <li>
                <a href="{% url 'hi:index' %}">Hightop</a>
            </li>

            <li>
                {% if user.is_authenticated %}
                    <a href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                    <a href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>

            <li>
                {% if not user.is_authenticated %}
                    <a href="{% url 'common:signup' %}">회원가입</a>
                {% endif %}
            </li>

            <li>
                <a href="{% url 'main:iindex' %}">게시판</a>
            </li>

            <li>
                <a href="{% url 'crawling:crawling' %}">크롤링</a>
            </li>

        </ul>

    </div>

</nav>

<script src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>
    $('nav li').hover(
        function() {
            $('ul', this).stop().slideDown(200);
        },
        function() {
            $('ul', this).stop().slideUp(200);
        }
    );
</script>

</body>
</html>